<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <title>Search Band</title>
</head>

<body>
    <!--Menu-->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="../index.html">BandMaker</a>
            </div>
        </nav>
    </header>

    <div class="container mt-3 text-center">
        <h2>Buscar Bandas</h2>
        <form class="col-sm-12 col-md-6 mb-2 mx-auto" class="row d-block mt-3" method="get" action="/pesquisaBanda/">
            <div class="input-group">
                <input type="text" name="busca" class="form-control" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary" type="submit" value="submit" id="button-addon1"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>


        <table class="table table-bordered table-hover">

            <tbody id="myTable">
                <?php
                if (isset($resultado)) {
                    if ($resultado != null) {
                        foreach ($resultado as $key => $value) {
                            echo '<tr>
                           <td class="d-flex">
                            <img class="img-fluid " src="../assets/img/' . $resultado[$key]['imagem'] . '">
                            <h4 class="my-auto mx-auto"> ' . $resultado[$key]['nome_usuario'] . '</h4>
                            <h4 class="my-auto mx-auto"> ' . $resultado[$key]['genero'] . '
                            </h4>       
                            </td>
                            </tr>';
                        }
                    } else {
                        echo '<h5 class="alert alert-danger">Banda inexistente ou digitada incorretamente</h5>';
                    }
                }
                ?>
            </tbody>
        </table>
    </div>

</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../js/app.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

</html>