<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/brands.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.css">
    <title>Search Band</title>
</head>

<body>
    <!--Menu-->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="../index.html">BandMaker</a>
            </div>
        </nav>
    </header>

    <div class="container my-3 text-center">
        <h1>Buscar Bandas</h1>
        <form class="col-sm-12 col-md-6 mb-2 mx-auto" class="row d-block my-4" method="get" action="/pesquisaBanda/">
            <div class="input-group">
                <input type="text" name="busca" class="form-control" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                <select class="custom-select ml-3 col-4" name="genero">
                    <option selected>Gênero</option>
                    <?php
                    if (isset($genero)) {
                        foreach ($genero as $key => $value) {
                            echo '<option>' . $genero[$key]['genero'] . '</option>';
                        }
                    }
                    ?>
                </select>
                <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary" type="submit" value="submit" id="button-addon1"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>

        <div class="col-8  mx-auto">
            <table class="table table-hover mt-4">
                <tbody>
                    <?php
                    if (isset($resultado)) {
                        if ($resultado != null) {
                            foreach ($resultado as $key => $value) {
                                echo '<tr>
                                <td>
                                    <img class="img-fluid" src="../assets/img/' . $resultado[$key]['imagem'] . '" style="max-height: 100px; max-width: 100px;">
                                </td>
                                <td>
                                     <h5>
                                        <a class="text-reset nav-link my-4" href="/perfil-banda/' . $resultado[$key]['nome_usuario'] . '">
                                        ' . $resultado[$key]['nome_usuario'] . '</a>             
                                    </h5>
                                </td>
                                <td>                                    
                                    <h5>
                                        <a class="text-reset nav-link my-4" href="/perfil-banda/' . $resultado[$key]['nome_usuario'] . '">
                                        ' . $resultado[$key]['genero'] . '</a>                         
                                    </h5>                                
                                </td>
                                </tr>';
                            }
                        } else {
                            echo '<h5 class="alert alert-danger">Banda inexistente ou digitada incorretamente</h5>';
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../js/app.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

</html>