<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <title>Search Band</title>
</head>

<body>
    <!--Menu-->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="../index.html">BandMaker</a>
            </div>
        </nav>
    </header>

    <div class="container mt-3 text-center">
        <h2>Buscar Bandas</h2>
        <input class="form-control" id="myInput" type="text" placeholder="Buscar">
        <br>
        <table class="table  table-bordered table-hover">

            <tbody id="myTable">
                <tr>
                    <td class="d-flex">
                        <img class="img-fluid w-25 " src="../assets/img/beatles.jpg">
                        <h4 class="my-auto mx-auto">The beatles</h4>
                        
                    </td>
                </tr>
                <tr>
                    <td class="d-flex ">
                        <img class="img-fluid w-25 " src="../assets/img/pj.jpg">
                        <h4 class="my-auto mx-auto">Pearl Jam</h4>
                    </td>
                </tr>
                <tr>
                    <td class="d-flex">
                        <img class="img-fluid w-25 " src="../assets/img/acdc.jpg">
                        <h4 class="my-auto mx-auto">ACDC</h4>
                    </td>
                </tr>
                <tr>
                    <td class="d-flex">
                        <img class="img-fluid w-25  " src="../assets/img/eye.png">
                        <h4 class="my-auto mx-auto">Grabbing Crabs</h4>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../js/app.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>


</html>