<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/all.min.css">
    <title>Novo Perfil</title>
</head>

<body>

    <!-- Menu -->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="../index.html">BandMaker</a>
            </div>
        </nav>
    </header>

    <div class="container pt-5">
        <div class="row class justify-content-center ">
            <div>
                <h2 class="mt-4">Crie seu Perfil</h2>
            </div>
        </div>

        <!-- Input de informações para cadastro -->
        <div class="row mt-5 justify-content-center">
            <div class="col-sm-12 col-md-12 justify-content-center ">

                <div class="col-sm-12 col-md-12 input-group mb-3 p-0 justify-content-center">

                    <form method="post" class="col-10" action="/criarConta/" enctype="multipart/form-data">

                        <!-- Usuário -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Usuário</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues']) && isset($action) && $action != 'user-alredy-exists') {
                                echo '<input name="nome_usuario" type="text" class="form-control" placeholder="Nome de usuário" aria-label="Username" aria-describedby="basic-addon1" value="' . $_SESSION['personValues']['nome_usuario'] . '">';
                            } else {
                                echo '<input name="nome_usuario" type="text" class="form-control" placeholder="Nome de usuário" aria-label="Username" aria-describedby="basic-addon1">';
                            }
                            ?>

                        </div>

                        <?php
                        if (isset($action) && $action == "user-alredy-exists") {
                            echo '<h5 class="alert alert-danger my-3">Erro: Nome já foi usado, escolha outro</h5>';
                        }
                        ?>

                        <!-- Senha -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Senha</span>
                            </div>
                            <input name="senha" type="password" class="form-control" placeholder="Digite sua senha" aria-label="Recipients username" aria-describedby="basic-addon2">
                        </div>

                        <!-- Confirmação Senha -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> Confirme a Senha</span>
                            </div>
                            <input name="confirmar-senha" type="password" class="form-control" placeholder="Digite sua senha" aria-label="Recipients username" aria-describedby="basic-addon2">
                        </div>

                        <!-- Mostra erro de confirmação de senha -->
                        <?php
                        if (isset($action) && $action == "passwords-not-equal") {
                            echo '<h5 class="alert alert-danger my-3">Erro: As senhas não batem!</h5>';
                        }
                        ?>

                        <!-- Nome Completo -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome Completo</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="nome" type="text" aria-label="First name" class="form-control
                                " placeholder="Nome" value="' . $_SESSION['personValues']['nome'] . '">';
                                echo '<input name="sobrenome" type="text" aria-label="Last name" class="form-control" placeholder="Sobrenome" value="' . $_SESSION['personValues']['sobrenome'] . '">';
                            } else {
                                echo '<input name="nome" type="text" aria-label="First name" class="form-control
                                " placeholder="Nome">';
                                echo '<input name="sobrenome" type="text" aria-label="Last name" class="form-control" placeholder="Sobrenome">';
                            }
                            ?>
                        </div>

                        <!-- Idade -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Idade</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="idade" type="number" aria-label="exp" class="form-control" placeholder="30" value="' . $_SESSION['personValues']['idade'] . '">';
                            } else {
                                echo '<input name="idade" type="number" aria-label="exp" class="form-control" placeholder="30">';
                            }
                            ?>
                        </div>

                        <!-- Telefone -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Telefone</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="telefone" type="text" aria-label="exp" class="form-control" placeholder="99999-8888" value="' . $_SESSION['personValues']['telefone'] . '">';
                            } else {
                                echo '<input name="telefone" type="text" aria-label="exp" class="form-control" placeholder="99999-8888">';
                            }
                            ?>
                        </div>


                        <!-- CEP -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CEP</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="cep" type="text" class="form-control " id="cep" size="10" maxlength="9" placeholder="00000000" value="' . $_SESSION['personValues']['cep'] . '">';
                            } else {
                                echo '<input name="cep" type="text" class="form-control " id="cep" size="10" maxlength="9" placeholder="00000000">';
                            }
                            ?>

                        </div>

                        <!-- Estado -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Estado</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="estado" type="text" class="form-control " id="uf" size="2" placeholder="SC" value="' . $_SESSION['personValues']['estado'] . '">';
                            } else {
                                echo '<input name="estado" type="text" class="form-control " id="uf" size="2" placeholder="SC">';
                            }
                            ?>
                        </div>

                        <!-- Cidade -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Cidade</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="cidade" type="text" class="form-control" id="cidade" size="40" placeholder="Blumenau" value="' . $_SESSION['personValues']['cidade'] . '">';
                            } else {
                                echo '<input name="cidade" type="text" class="form-control" id="cidade" size="40" placeholder="Blumenau">';
                            }
                            ?>
                        </div>

                        <!-- Rua -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Rua</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="rua" type="text" class="form-control " id="rua" size="60" placeholder="Rua Antônio da Veiga" value="' . $_SESSION['personValues']['rua'] . '">';
                            } else {
                                echo '    <input name="rua" type="text" class="form-control " id="rua" size="60" placeholder="Rua Antônio da Veiga">';
                            }
                            ?>
                        </div>

                        <!-- Email -->
                        <div class="input-group ">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Email</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="email" type="text" class="form-control" placeholder="exemplo@bandmaker" aria-label="Recipients username" aria-describedby="basic-addon2" value="' . $_SESSION['personValues']['email'] . '">';
                            } else {
                                echo '<input name="email" type="text" class="form-control" placeholder="exemplo@bandmaker" aria-label="Recipients username" aria-describedby="basic-addon2">';
                            }
                            ?>
                        </div>

                        <!-- Instrumento -->
                        <div class="my-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="inputGroupSelect01">Instrumento</label>
                            </div>
                            <div class="col-3 mb-2 form-check form-check-inline">
                                <input name="guitarra" class="form-check-input" type="checkbox" id="inlineCheckbox1" value="Guitarra">
                                <label class="form-check-label" for="inlineCheckbox1">Guitarra</label>
                            </div>
                            <div class="col-3 form-check form-check-inline">
                                <input name="baixo" class="form-check-input" type="checkbox" id="inlineCheckbox2" value="Baixo">
                                <label class="form-check-label" for="inlineCheckbox2">Baixo</label>
                            </div>
                            <div class="col-3 form-check form-check-inline">
                                <input name="teclado" class="form-check-input" type="checkbox" id="inlineCheckbox3" value="Teclado">
                                <label class="form-check-label" for="inlineCheckbox3">Teclado</label>
                            </div>
                            <div class="col-3 form-check form-check-inline">
                                <input name="piano" class="form-check-input" type="checkbox" id="inlineCheckbox4" value="Piano">
                                <label class="form-check-label" for="inlineCheckbox4">Piano</label>
                            </div>
                            <div class="col-3 form-check form-check-inline">
                                <input name="pandeiro" class="form-check-input" type="checkbox" id="inlineCheckbox5" value="Pandeiro">
                                <label class="form-check-label" for="inlineCheckbox5">Pandeiro</label>
                            </div>
                            <div class="col-3 form-check form-check-inline">
                                <input name="gaita" class="form-check-input" type="checkbox" id="inlineCheckbox6" value="Gaita">
                                <label class="form-check-label" for="inlineCheckbox6">Gaita</label>
                            </div>
                            <div class="col-3 form-check form-check-inline">
                                <input name="bateria" class="form-check-input" type="checkbox" id="inlineCheckbox7" value="Bateria">
                                <label class="form-check-label" for="inlineCheckbox7">Bateria</label>
                            </div>
                            <div class="col-3 form-check form-check-inline">
                                <input name="vocal" class="form-check-input" type="checkbox" id="inlineCheckbox8" value="Vocal">
                                <label class="form-check-label" for="inlineCheckbox8">Vocal</label>
                            </div>
                            <div class="col-5 form-check form-check-inline">
                                <input name="outros" class="form-check-input" type="checkbox" id="inlineCheckbox9">
                                <label class="form-check-label mr-3" for="inlineCheckbox9">Outros</label>
                                <input name="outros-input" type="text" class="form-control" placeholder="Ex: Escaleta, Hurdy Gurdy">
                            </div>
                        </div>

                        <!-- Experiencia -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Experiência</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<input name="tempo" type="number" aria-label="exp" placeholder="2 anos" class="form-control" value="' . $_SESSION['personValues']['tempo'] . '">';
                            } else {
                                echo '<input name="tempo" type="number" aria-label="exp" placeholder="2 anos" class="form-control">';
                            }
                            ?>

                        </div>


                        <!-- INFLUENCIAS -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Influencias</span>
                            </div>
                            <?php
                            if (isset($_SESSION['personValues'])) {
                                echo '<textarea name="influencia" class="form-control" placeholder="Banda Tigres do axé 
Quenn"  aria-label="With textarea">' . $_SESSION['personValues']['influencia'] . '</textarea>';
                            } else {
                                echo '<textarea name="influencia" class="form-control" placeholder="Banda Tigres do axé 
Quenn"  aria-label="With textarea"></textarea>';
                            }
                            ?>
                        </div>

                        <!-- ADD Imagem -->
                        <div class="border border-light border-radius-3 col-6 w-25">
                            <p class="text-secondary">Adicione uma Imagem da banda</p>
                            <div>
                                <input name="img" type="file" id="imgload">
                                <img class="mt-2 img-fluid mx-auto" src="#" id="imgshow" align="left">
                            </div>
                        </div>
                        <?php
                        if (isset($action) && $action == "blank-fields") {
                            echo '<h5 class="alert alert-danger">Erro: Preencha todos os campos obrigatórios!</h5>';
                        } else if (isset($action) && $action == "email-not-valid") {
                            echo '<h5 class="alert alert-danger">Erro: O email não é válido!</h5>';
                        } else if (isset($action) && $action == "not-an-image") {
                            echo '<h5 class="alert alert-danger">Erro: O arquivo não é uma imagem!</h5>';
                        } else if (isset($action) && $action == "img-too-big") {
                            echo '<h5 class="alert alert-danger">Erro: Imagem muito grande!</h5>';
                        } else if (isset($action) && $action == "incorrect-format") {
                            echo '<h5 class="alert alert-danger">Erro: Formato incompatível, a imagem deve ser jpg, jpeg ou png!</h5>';
                        }
                        ?>
                        <div class="col-sm-12 col-md-4 ml-auto my-1">
                            <button type="submit" class="btn btn-dark btn-lg w-100">Criar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <nav class="navbar navbar-fixed-bottom navbar-dark bg-dark  p-0 mt-5">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright BandMaker 2019</a>
            </div>
        </nav>
    </footer>

</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../js/app.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

</html>