<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Crie sua Banda</title>
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
</head>

<body>
    <!-- NAV BAR  -->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="../index.html">BandMaker</a>
            </div>
        </nav>
    </header>
    <!-- FIM NAV BAR -->

    <div class="container mt-4 ">

        <div class="row class justify-content-center ">
            <div>
                <h2 class="mt-4">Cadastre sua Banda</h2>
            </div>
        </div>

        <div class="row mt-5 justify-content-center">
            <div class="col-sm-12 col-md-12 justify-content-center ">

                <div class="col-sm-12 col-md-12 input-group mb-3 p-0 justify-content-center">
                    <form method="post" class="col-10" action="/criarBanda/">

                        <!-- Nome -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome da Banda</span>
                            </div>
                            <input name="nome" type="text" class="form-control" placeholder="Prog Bulls" aria-label="Username" aria-describedby="basic-addon1">
                        </div>

                        <!-- Senha -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Senha</span>
                            </div>
                            <input name="senha" type="password" class="form-control" placeholder="*******" aria-label="Recipient's username" aria-describedby="basic-addon2">
                        </div>

                        <!-- Confirmação Senha -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> Confirme a Senha</span>
                            </div>
                            <input type="password" class="form-control" placeholder="*******" aria-label="Recipient's username" aria-describedby="basic-addon2">
                        </div>

                        <!-- Telefone -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Telefone</span>
                            </div>
                            <input name="telefone" type="text" aria-label="exp" class="form-control" placeholder="0000000000">
                        </div>


                        <!-- CEP -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CEP</span>
                            </div>
                            <input name="cep" type="text" class="form-control " id="cep" value="" size="10" maxlength="9" placeholder="000000000" /></label>
                        </div>

                        <!-- Estado -->
                        <div class="input-group ">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Estado</span>
                            </div>
                            <input name="estado" type="text" class="form-control " id="uf" size="2" placeholder="SC" /></label>
                        </div>

                        <!-- Cidade -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Cidade</span>
                            </div>

                            <input name="cidade" type="text" class="form-control" id="cidade" size="40" placeholder="Blumenau" /></label>
                        </div>

                        <!-- Rua -->
                        <div class="input-group ">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Rua</span>
                            </div>
                            <input name="rua" type="text" class="form-control " id="rua" size="60" placeholder="Rua Almeida José Pereira" /></label>
                        </div>

                        <!-- Email -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Email</span>
                            </div>
                            <input name="email" type="text" class="form-control" placeholder="random@anon.com" aria-label="Recipient's username" aria-describedby="basic-addon2">
                        </div>

                        <!-- INFLUENCIAS -->
                        <div class="input-group ">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Influencias</span>
                            </div>
                            <textarea name="influencias" class="form-control" aria-label="With textarea" placeholder="Banda XxXMaker
Banda Rodinha De Bicicleta
Banda do sul"></textarea>
                        </div>
                        <!-- Descrição da Banda -->

                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Descrição da Banda</span>
                            </div>
                            <textarea name="descricao" class="form-control" placeholder="Banda de garagem com objetivo de se tornar Deuses do Rock assim como em Guitar HERO III  "></textarea>
                        </div>

                        <!-- ADD Imagem -->
                        <div class="border border-light border-radius-3 col-6 w-25 h-25">
                            <p class="text-secondary">Adicione uma Imagem da banda</p>
                            <div>
                                <input name="img" type="file" id="imgload">
                                <img class="mt-2 img-fluid mx-auto" src="#" id="imgshow" align="left">
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-4 ml-auto my-4">
                            <button type="submit" class="btn btn-dark btn-lg w-100">Criar</button>
                            <?php
                            if ($cadastroError) {
                                echo '<h5 class="alert alert-danger">Erro: Não foi possível criar Banda</h5>';
                            }
                            ?>
                        </div>


                    </form>


                </div>

            </div>

        </div>
    </div>

</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../js/app.js"></script>

</html>