<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Crie sua Banda</title>
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
</head>

<body>
    <!-- NAV BAR  -->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="../index.html">BandMaker</a>
            </div>
        </nav>
    </header>
    <!-- FIM NAV BAR -->

    <div class="container mt-4 ">

        <div class="row class justify-content-center ">
            <div>
                <h2 class="mt-4">Cadastre sua Banda</h2>
            </div>
        </div>

        <div class="row mt-5 justify-content-center">
            <div class="col-sm-12 col-md-12 justify-content-center ">

                <div class="col-sm-12 col-md-12 input-group mb-3 p-0 justify-content-center">
                    <form method="post" class="col-10" action="/criarBanda/" enctype="multipart/form-data">

                        <!-- Nome -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome da Banda</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues']) && isset($action) && $action != 'user-alredy-exists') {
                                echo '<input type="text" class="form-control" placeholder="Prog Bulls" name="nome_usuario" ria-label="Username" aria-describedby="basic-addon1" value="'.$_SESSION['bandValues']['nome_usuario'].'">';
                            } else {
                                echo '<input type="text" class="form-control" placeholder="Prog Bulls" name="nome_usuario" ria-label="Username" aria-describedby="basic-addon1">';
                            }
                            ?>

                            

                        </div>

                        <?php
                        if (isset($action) && $action == "band-alredy-exists") {
                            echo '<h5 class="alert alert-danger my-3">Erro: Nome já foi usado, escolha outro</h5>';
                        }
                        ?>

                        <!-- Senha -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Senha</span>
                            </div>
                            <input name="senha" type="password" class="form-control" placeholder="Digite sua senha" aria-label="Recipient's username" aria-describedby="basic-addon2">
                        </div>

                        <!-- Confirmação Senha -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> Confirme a Senha</span>
                            </div>
                            <input name="confirmar-senha" type="password" class="form-control" placeholder="Digite sua senha" aria-label="Recipient's username" aria-describedby="basic-addon2">

                        </div>

                        <!-- Mostra erro de confirmação de senha -->
                        <?php
                        if (isset($action) && $action == "passwords-not-equal") {
                            echo '<h5 class="alert alert-danger my-3">Erro: As senhas não batem!</h5>';
                        }
                        ?>

                        <!-- Telefone -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Telefone</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<input name="telefone" type="number" aria-label="exp" class="form-control" placeholder="912345698" value="'. $_SESSION['bandValues']['telefone'] .'">';
                            } else {
                                echo '<input name="telefone" type="number" aria-label="exp" class="form-control" placeholder="912345698">';
                            }
                            ?>
                            
                        </div>

                        <!-- CEP -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CEP</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<input name="cep" type="text" class="form-control " id="cep" size="10" maxlength="9" placeholder="000000000" value="'.$_SESSION['bandValues']['cep'].'">';
                            } else {
                                echo '<input name="cep" type="text" class="form-control " id="cep" size="10" maxlength="9" placeholder="000000000">';
                            }
                            ?>
                           
                        </div>

                        <!-- Estado -->
                        <div class="input-group ">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Estado</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<input name="estado" type="text" class="form-control " id="uf" size="2" placeholder="Informe o CEP" value="'. $_SESSION['bandValues']['estado'] .'">';
                            } else {
                                echo '<input name="estado" type="text" class="form-control " id="uf" size="2" placeholder="Informe o CEP"';
                            }
                            ?>
                            
                        </div>

                        <!-- Cidade -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Cidade</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<input name="cidade" type="text" class="form-control" id="cidade" size="40" placeholder="Informe o CEP" value="'. $_SESSION['bandValues']['cidade'] .'">';
                            } else {
                                echo '<input name="cidade" type="text" class="form-control" id="cidade" size="40" placeholder="Informe o CEP">';
                            }
                            ?>
                        </div>

                        <!-- Rua -->
                        <div class="input-group ">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Rua</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<input name="rua" id="rua" type="text" class="form-control" size="60" placeholder="Informe o CEP" value="'. $_SESSION['bandValues']['rua'] .'">';
                            } else {
                                echo '<input name="rua" id="rua" type="text" class="form-control" size="60" placeholder="Informe o CEP">';
                            }
                            ?>
                            
                        </div>

                        <!-- Email -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Email</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<input name="email" type="text" class="form-control" placeholder="exemplo@bandmaker.com" aria-label="Recipients username" aria-describedby="basic-addon2" value="'. $_SESSION['bandValues']['email'] .'">';
                            } else {
                                echo '<input name="email" type="text" class="form-control" placeholder="exemplo@bandmaker.com" aria-label="Recipients username" aria-describedby="basic-addon2">';
                            }
                            ?>
                            
                        </div>

                        <!-- Gênero -->
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Gênero</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<input name="genero" type="text" class="form-control" size="60" placeholder="Ex: Rock" value="'. $_SESSION['bandValues']['genero'] .'">';
                            } else {
                                echo '<input name="genero" type="text" class="form-control" size="60" placeholder="Ex: Rock">';
                            }
                            ?>
                            
                        </div>

                        <!-- INFLUENCIAS -->
                        <div class="input-group my-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Influencias</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<textarea name="influencias" class="form-control" placeholder="Queens" aria-label="With textarea">'. $_SESSION['bandValues']['influencias'] .'</textarea>';
                            } else {
                                echo '<textarea name="influencias" class="form-control" placeholder="Queens" aria-label="With textarea"></textarea>';
                            }
                            ?>
                            
                        </div>
                        <!-- Descrição da Banda -->

                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Descrição da Banda</span>
                            </div>
                            <?php
                            if(isset($_SESSION['bandValues'])) {
                                echo '<textarea name="descricao" class="form-control" placeholder="">'. $_SESSION['bandValues']['descricao'] .'</textarea>';
                            } else {
                                echo '<textarea name="descricao" class="form-control" placeholder=""></textarea>';
                            }
                            ?>
                            
                        </div>

                        <!-- ADD Imagem -->
                        <div class="col-sm-12 col-md-6">
                            <div class="border border-light border-radius-3 col-6">
                                <p class="text-secondary">Adicione uma Imagem da banda</p>
                                <div>
                                    <input name="img" type="file" id="imgload">
                                    <img class="mt-2 img-fluid mx-auto" src="#" id="imgshow" align="left">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <?php
                            if (isset($action) && $action == "blank-fields") {
                                echo '<h5 class="alert alert-danger">Erro: Preencha todos os campos obrigatórios!</h5>';
                            } else if (isset($action) && $action == "email-not-valid"){
                                echo '<h5 class="alert alert-danger">Erro: O email não é válido!</h5>';
                            } else if(isset($action) && $action == "img-too-big") {
                                echo '<h5 class="alert alert-danger">Erro: Imagem muito grande!</h5>';
                            } else if(isset($action) && $action == "incorrect-format") {
                                echo '<h5 class="alert alert-danger">Erro: Formato incompatível, a imagem deve ser jpg, jpeg ou png!</h5>';
                            }
                            ?>
                        </div>
                        <div class="col-sm-12 col-md-4 ml-auto my-1">
                            <button type="submit" class="btn btn-dark btn-lg w-100">Criar</button>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <nav class="navbar navbar-fixed-bottom navbar-dark bg-dark  p-0 mt-5">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright BandMaker 2019</a>
            </div>
        </nav>
    </footer>
</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../js/app.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

</html>