<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BandMaker</title>
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/all.min.css">

</head>

<body>
    <!--Menu-->
    <header id="beggining">

        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark p-0">
            <a class="navbar-brand ml-4" href="/">BandMaker</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse content-center" id="navbarText">
                <ul class="navbar-nav d-flex bd-highlight">
                    <li class="nav-item active">
                        <!-- Exibe nome do usuário logado para redirecionar ao seu perfil -->
                        <?php
                        if ($banda) {
                            echo '<a class="nav-link" href="/perfil-banda/' . $perfil[0]['nome_usuario'] . '">Banda: ' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
                        } else {
                            echo '<a class="nav-link" href="/perfil/' . $perfil[0]['nome_usuario'] . '">' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
                        }
                        ?>
                    </li>
                    <!-- Cria botões que aparecem quando logado -->
                    <?php
                        if ($banda || isset($perfil[0]['banda_id'])) {
                            echo '<li class="nav-item bd-highlight">';
                            echo '<a class="nav-link" href="/eventos/">Eventos</a>';
                            echo '</li>';
                        }

                        if ($banda || !isset($perfil[0]['banda_id'])) {
                            echo '<li class="nav-item bd-highlight">';
                            echo '<a class="nav-link" href="/vagas/">Vagas</a>';
                            echo '</li>';
                        }
                        echo '<li class="nav-item bd-highlight">';
                        echo '<a class="nav-link" href="/notificacoes/">Notificações</a>';
                        echo '</li>';
                   
                        echo '<li class="nav-item bd-highlight">';
                        echo '<a class="nav-link" href="/logout">Deslogar</a>';
                        echo '</li>';
                    ?>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container mt-5">

        <!-- titulo -->
        <div class="row justify-content-center">
            <?php
            echo '<h2 class="text-muted my-5">Eventos de ' . $nome_banda . '</h2>';
            ?>
        </div>

        <!-- lista de eventos -->
        <div class="row">
            <!-- input de pesquisa -->

            <div class="col-sm-12 col-md-<?php if ($banda) {
                                                echo '4';
                                            } else {
                                                echo '6';
                                            } ?> mb-2 mx-auto">

                <div class="input-group">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon1"><i class="fas fa-search"></i></button>
                    </div>
                    <input type="text" class="form-control" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                </div>
            </div>
            <?php
            if ($banda) {
                echo '<div class="col-sm-12 col-md-4 mb-auto d-flex justify-content-center">
                <a class="btn btn-outline-secondary" href="/criar-evento/">Criar Evento</a>
                </div>';
            }
            ?>

            <div class="col-sm-12 col-md-<?php if ($banda) {
                                                echo '4';
                                            } else {
                                                echo '6';
                                            } ?> mb-2">
                <!--calendário -->
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 p-0">
                            <div class="form-group">
                                <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                                    <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4" />
                                    <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- eventos -->
        <div class="row">
            <div class="col-sm-12">
                <div class="accordion" id="accordionExample">
                    <?php
                    if ($eventos != null) {
                        foreach ($eventos as $key => $value) {
                            echo '<div class="card"><div class="card-header" id="heading' . $key . '"><h2 class="mb-0">';
                            echo '<button class="btn btn-link text-reset" type="button" data-toggle="collapse"
                                data-target="#collapse' . $key . '" aria-expanded="true" aria-controls="collapse' . $key . '">
                                ' . $eventos[$key]['nome_evento'] . '</button>';
                            echo '</button></h2></div>';
                            echo '<div id="collapse' . $key . '" class="collapse" aria-labelledby="heading' . $key . '"data-parent="#accordionExample"><div class="card-body">';
                            echo $eventos[$key]['descricao'];
                            echo '</div></div></div>';
                        }
                    } else {
                        echo '<h4 class="text-muted">Nenhum evento marcado</h4>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer>
        <nav class="navbar navbar-fixed-bottom navbar-dark bg-dark p-0 mt-5">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright BandMaker 2019</a>
            </div>
        </nav>
    </footer>

</body>

<script src="../js/jquery-3.3.1.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/moment-develop/min/moment.min.js"></script>
<script src="../vendor/bootstrap4-datetime-picker-rails-master/vendor/assets/javascripts/tempusdominus-bootstrap-4.min.js"></script>
<script src="../js/app.js"></script>

</html>