<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BandMaker</title>
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/all.min.css">

</head>

<body>
    <!-- Menu -->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <!-- Mantém logado ao voltar para o início -->
                <a class="navbar-brand mx-auto" href="/">BandMaker</a>
            </div>
        </nav>
    </header>

    <div class="container mt-5">

        <!-- titulo -->
        <div class="row justify-content-center">
            <?php
            
            echo '<h2 class="text-muted my-5">Eventos de '. $nome_banda .'</h2>';
            ?>
        </div>

        <!-- lista de eventos -->
        <div class="row">
            <!-- input de pesquisa -->
            <div class="col-sm-12 col-md-6 mb-2 mx-auto">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-secondary" type="button" id="button-addon1"><i
                                class="fas fa-search"></i></button>
                    </div>
                    <input type="text" class="form-control" placeholder="" aria-label="Example text with button addon"
                        aria-describedby="button-addon1">
                </div>

            </div>
            <div class="col-sm-12 col-md-6 mb-2">
                <!--calendário -->
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 p-0">
                            <div class="form-group">
                                <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                                    <input type="text" class="form-control datetimepicker-input"
                                        data-target="#datetimepicker4" />
                                    <div class="input-group-append" data-target="#datetimepicker4"
                                        data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <!-- eventos -->
        <div class="row">
            <div class="col-sm-12">
                <div class="accordion" id="accordionExample">
                    <?php
                        if($eventos != null) {
                            foreach ($eventos as $key => $value) {
                                echo '<div class="card"><div class="card-header" id="heading'.$key.'"><h2 class="mb-0">';
                                echo '<button class="btn btn-link text-reset" type="button" data-toggle="collapse"
                                data-target="#collapse'.$key.'" aria-expanded="true" aria-controls="collapse'.$key.'">
                                '. $eventos[$key]['nome_evento'] .'</button>';
                                echo '</button></h2></div>';
                                echo '<div id="collapse'.$key.'" class="collapse" aria-labelledby="heading'.$key.'"data-parent="#accordionExample"><div class="card-body">';
                                echo $eventos[$key]['descricao'];
                                echo '</div></div></div>';
                            }
                            
                        } else {
                            echo '<h4 class="text-muted">Nenhum evento marcado</h4>';
                        }
                    
                    ?>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0 fixed-bottom">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright</a>
            </div>
        </nav>
    </footer>

</body>


<script src="../js/jquery-3.3.1.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/moment-develop/min/moment.min.js"></script>
<script
    src="../vendor/bootstrap4-datetime-picker-rails-master/vendor/assets/javascripts/tempusdominus-bootstrap-4.min.js"></script>
<script src="../js/app.js"></script>

</html>