<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>BandMaker</title>
</head>

<body>
    <!--Menu-->
    <header id="beggining">
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark p-0">
            <a class="navbar-brand ml-4" href="/">BandMaker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse content-center" id="navbarText">
                <ul class="navbar-nav d-flex bd-highlight">
                    <li class="nav-item active">
                        <a class="nav-link" href="login/">Login/Cadastrar<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item bd-highlight">
                        <a class="nav-link" href="#qs">Quem Somos</a>
                    </li>
                    <li class="nav-item bd-highlight">
                        <a class="nav-link" href="#cf">Como funciona</a>
                    </li>
                    <li class="nav-item bd-highlight">
                        <a class="nav-link" href="eventos/">Eventos</a>
                    </li>
                    <li class="nav-item ml-auto bd-highlight">
                    <?php
                    if($perfil_normal != null) {
                        echo '<a class="nav-link" href="perfil/'. $perfil_normal[0]['id'] .'" id="profileLink">';
                        echo $perfil_normal[0]['nome'];
                        echo '</a>';
                    }
                    ?>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container my-5">
        <section class="text-center">
            <div class="row">
                <div class="col-12">
                    <h1>Band Maker: encontre sua banda</h1>
                </div>
                <div class="col-12">
                    <img class="img-fluid mx-auto w-100 d-block rounded my-0" src="../assets/img/crowd.jpg" alt="">
                </div>
                <!-- Pesquisa -->
                <div class="row mt-4 justify-content-center mx-auto">
                    <div class="col-md-4 col-sm-12 ">
                        <div class="card ">
                            <img class="card-img-top" src="assets/img/searchBand.png">
                            <div class="card-body">
                                <h5 class="card-title">Procurar Bandas</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="card ">
                            <img class="card-img-top" src="assets/img/startBand.png">
                            <div class="card-body">
                                <h5 class="card-title">Criar Banda</h5>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>

        <section class="mt-3 text-center">
            <!-- Como funciona -->
            <div id="cf" class="row">
                <div class="col-12">
                    <div class="jumbotron py-2">
                        <h2 class="display-5">Como funciona</h2>
                        <article>
                            <p class="text-justify">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, ducimus,
                                necessitatibus non dolorem consectetur vitae minima consequatur aut praesentium
                                recusandae
                                architecto, debitis culpa sapiente? Placeat, dolorum quo. Reiciendis, fuga quas.
                            </p>
                        </article>
                    </div>
                </div>
            </div>
            <!-- Quem Somos -->
            <div id="qs" class="row">
                <div class="col-12">
                    <div class="jumbotron py-2 ">
                        <h2 class="display-5 ">Quem somos</h2>
                        <article>
                            <p class="text-justify">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, ducimus,
                                necessitatibus non dolorem consectetur vitae minima consequatur aut praesentium
                                recusandae
                                architecto, debitis culpa sapiente? Placeat, dolorum quo. Reiciendis, fuga quas.
                            </p>
                        </article>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Footer -->
    <footer>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0 fixed-bottom">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright</a>
            </div>
        </nav>
    </footer>


</body>
<script src="js/jquery-3.3.1.js"></script>
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>

</html>