<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>BandMaker</title>
</head>

<body>
    <!--Menu-->
    <header id="beggining">

        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark p-0">
            <a class="navbar-brand ml-4" href="/">BandMaker</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse content-center" id="navbarText">
                <ul class="navbar-nav d-flex bd-highlight">
                    <li class="nav-item active">
                        <!-- Caso não logado, exibe "Login/cadastrar"
                    Caso logado, exibe o nome do perfil -->
                        <?php
                        if (isset($perfil)) {
                            if ($banda) {
                                echo '<a class="nav-link" href="/perfil-banda/' . $perfil[0]['nome_usuario'] . '">Banda: ' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
                            } else {
                                echo '<a class="nav-link" href="/perfil/' . $perfil[0]['nome_usuario'] . '">' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
                            }
                        } else {
                            echo '<a class="nav-link" href="/login/">Login/Cadastrar<span class="sr-only">(current)</span></a>';
                        }
                        ?>
                    </li>
                    <li class="nav-item bd-highlight">
                        <a class="nav-link" href="#sb">Saiba Mais</a>
                    </li>
                    <!-- Cria o botão de evento caso esteja logado -->
                    <?php
                    if (isset($perfil)) {
                        echo '<li class="nav-item bd-highlight">';
                        echo '<a class="nav-link" href="/eventos/">Eventos</a>';
                        echo '</li>';
                    }
                    ?>
                    <!-- Cria o botão sair caso esteja logado -->
                    <?php
                    if (isset($perfil)) {
                        echo '<li class="nav-item bd-highlight">';
                        echo '<a class="nav-link" href="/logout">Sair</a>';
                        echo '</li>';
                    }
                    ?>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container my-5">
        <section class="text-center">
            <div class="row">
                <div class="col-12">
                    <h1>Band Maker: encontre sua banda</h1>
                </div>
                <div class="col-12">
                    <img class="img-fluid mx-auto w-100 d-block rounded my-0" src="../assets/img/crowd.jpg" alt="">
                </div>
                <!-- Pesquisa -->
                <div class="row mt-4 justify-content-center mx-auto">
                    <div class="col-md-4 col-sm-12 ">
                        <div class="card ">
                            <a class="btn btn-light p-0" href="/pesquisaBanda/" role="button">
                                <img class="card-img-top" src="assets/img/searchBand.png">
                                <div class="card-body">
                                    <h5 class="card-title">Procurar Bandas</h5>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="card">
                            <a class="btn btn-light p-0" href="criarBanda/" role="button">
                                <img class="card-img-top" src="assets/img/startBand.png">
                                <div class="card-body">
                                    <h5 class="card-title">Criar Banda</h5>
                                </div>
                            </a>

                        </div>

                        </button>

                    </div>

                </div>
            </div>
    </div>
    </section>

    <section class="mt-3 text-center">
        <!-- Como funciona -->

        <div class="col-12" id="sb">
            <div class="jumbotron py-2">
                <h2 class="display-5">Como funciona</h2>
                <article>
                    <p class="text-justify">
                        Nosso sistema possibilita a criação e gerenciamneto de bandas, sempre objetivando a praticidade,
                        usabilidade e organização, é possível <a href="criarBanda/" class="text-decoration-none">criar um perfil de banda</a>, procurar e adicionar membros,
                        <a href="/eventos/" class="text-decoration-none">organizar eventos</a> e encontros de bandas, além disso há possibilidede de <a href="/criarConta/" class="text-decoration-none">criar também um perfil individual</a> ,
                        o qual será visível para bandas que procuram novos integrantes.
                    </p>
                </article>
            </div>
        </div>

        <!-- Quem Somos -->

        <div class="col-12">
            <div class="jumbotron py-2 ">
                <h2 class="display-5 ">Quem somos</h2>
                <article>
                    <p class="text-justify">
                        Nosso grupo é composto por quatro alunos do SENAI de Blumenau, foi proposto ao grupo o desenvolvimento
                        de um site, e nossa proposta foi um projeto que pudesse atender a uma necessidade real de um certo grupo
                        de pessoas, o resultado foi esse site :)

                    </p>
                </article>
            </div>
        </div>

    </section>
    </div>
    <!-- Footer -->
    <footer>
        <nav class="navbar navbar-fixed-bottom navbar-dark bg-dark p-0 mt-5">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright BandMaker 2019</a>
            </div>
        </nav>
    </footer>

</body>
<script src="js/jquery-3.3.1.js"></script>
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>

</html>