<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <title>Login</title>
</head>

<body>
    <!--Menu-->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="/">BandMaker</a>
            </div>
        </nav>
    </header>

    <div class="container text-center mt-5">
        <div class="row ">
            <div class="col-12">
                <h2>Login</h2>
            </div>

            <div class="col-12 mt-2">
                <!-- Img -->
                <img class="img-fluid mx-auto w-25 d-block" src="../assets/img/login.png" alt="">
                <!-- Email + Senha -->
                <form class="row d-block mt-3" method="post" action="/login/">
                    <div class="form-group mx-auto mb-2 col-6">
                        <input type="text" name="user" class="form-control" placeholder="Nome de Usuário">
                    </div>
                    <div class="form-group mx-auto mb-2 col-6">
                        <input type="password" name="senha" class="form-control" id="inputPassword" placeholder="Password">
                    </div>

                    <div class="col-6 mx-auto" id="loginBox">
                        <!-- Mostra mensagem de erro no login -->
                        <?php 
                        if($loginError) {
                            echo '<h5 class="alert alert-danger">Erro: Login ou Senha incorretos!</h5>';
                        } 
                        ?>
                        <button type="submit" class="btn btn-dark btn-lg w-25">Login</button>
                        <a class="btn btn-dark btn-lg w-25" href="/criarConta/" role="button">Criar Conta</a>                        
                    </div>

                </form>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0 fixed-bottom">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright</a>
            </div>
        </nav>
    </footer>
</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

</html>