<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/brands.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.css">
    <title>Vagas</title>
</head>

<body>
    <!--Menu-->
    <header id="beggining">

        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark p-0">
            <a class="navbar-brand ml-4" href="/">BandMaker</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse content-center" id="navbarText">
                <ul class="navbar-nav d-flex bd-highlight">
                    <li class="nav-item active">
                        <!-- Exibe nome do usuário logado para redirecionar ao seu perfil -->
                        <?php
                        if ($banda) {
                            echo '<a class="nav-link" href="/perfil-banda/' . $perfil[0]['nome_usuario'] . '">Banda: ' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
                        } else {
                            echo '<a class="nav-link" href="/perfil/' . $perfil[0]['nome_usuario'] . '">' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
                        }
                        ?>
                    </li>
                    <!-- Cria botões que aparecem quando logado -->
                    <?php
                        if ($banda || isset($perfil[0]['banda_id'])) {
                            echo '<li class="nav-item bd-highlight">';
                            echo '<a class="nav-link" href="/eventos/">Eventos</a>';
                            echo '</li>';
                        }

                        if ($banda || !isset($perfil[0]['banda_id'])) {
                            echo '<li class="nav-item bd-highlight">';
                            echo '<a class="nav-link" href="/vagas/">Vagas</a>';
                            echo '</li>';
                        }
                        echo '<li class="nav-item bd-highlight">';
                        echo '<a class="nav-link" href="/notificacoes/">Notificações</a>';
                        echo '</li>';
                   
                        echo '<li class="nav-item bd-highlight">';
                        echo '<a class="nav-link" href="/logout">Deslogar</a>';
                        echo '</li>';
                    ?>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container my-5 text-center">
        <h1 class="text-muted">Notificações</h1>
        <?php
        if ($notificacoes != null) {
            echo '
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">Descrição</th>
                            <th scope="col">Ação</th>
                        </tr>
                    </thead>
                    <tbody>';
                    foreach ($notificacoes as $key => $value) {
                        echo '<tr>';
                            echo '<td>'. $notificacoes[$key]['titulo'] .'</td>';
                            echo '<td>'. $notificacoes[$key]['descricao'] .'</td>';
                            if($notificacoes[$key]['titulo'] == 'Convite') {
                          echo '<td>
                                <div class="btn-group">
                                <form method="post" action="/notificacoes/">
                                <input type="hidden" name="pedido_id" value="' . $notificacoes[$key]['pedido_id'] . '">
                                <input type="hidden" name="botao" value="aceitar">
                                <button class="btn btn-success" type="submit">Aceitar</button>
                                </form>
                                <form method="post" action="/notificacoes/">
                                <input type="hidden" name="botao" value="recusar">
                                <input type="hidden" name="pedido_id" value="' . $notificacoes[$key]['pedido_id'] . '">
                                <button class="btn btn-danger" type="submit">Recusar</button>
                                </form>
                                </div>
                                </td>';
                            } else {
                                echo '
                                <td>
                                <div class="btn-group">
                                <form method="post" action="/notificacoes/">
                                <input type="hidden" name="notificacao_id" value="' . $notificacoes[$key]['id'] . '">
                                <input type="hidden" name="botao" value="mensagem">
                                <button class="btn btn-danger" type="submit">OK</button>
                                </form>
                                ';
                            }
                        echo '</tr>';
                    }
               
               echo '</tbody>
            </table>
                ';
        } else {
            echo '<h5>Você não tem nenhuma notificação!</h5>';
        }
        ?>
    
    </div>
</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../js/app.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

</html>