<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Person Profile</title>
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">    
</head>

<body>
    <!--Menu-->
    <header id="beggining">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="../index.html">BandMaker</a>
            </div>
        </nav>
    </header>

    <div class="container mt-5">

        <div class="row justify-content-center">
            
                <h1 class="mt-4">Perfil Profissional</h1>
           
        </div>

        <div class="row mt-4">
            <div class="col-sm-12 col-md-8 d-flex">
                <img class src="../assets/img/luan.jpg" width="185" height="145">
                <ul id="ul1">
                    <li>Luan Santana</li>
                    <li>Sertanejo</li>
                    <li>Amo minhas fãs</li>
                </ul>
            </div>
                    
            
        </div>

        <div class="row mt-6 pt-5">

            <div class="col-sm-4 col-md-0 margin-left-0">
                <ul class="list-group">
                    <li class="list-group-item">Campo Grande</li>
                    <li class="list-group-item">28 anos</li>
                    <li class="list-group-item">Violão e Vocal</li>
                </ul>
            </div>

            <div class="col-sm-8 col-md-0 margin-left-0">

                <ul>
                    <li class="list-group-item">BANDAS:</li>
                    <li class="list-group-item">Banda Luan Santana</li>

                </ul>
            </div>

        </div>

    </div>
</body>

<script src="../js/jquery-3.3.1.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>



</html>