<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Person Profile</title>
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
</head>

<body>
    <!--Menu-->
    <?php
    if (isset($_SESSION['loginID'])) {
        echo '
        <header id="beggining">

        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark p-0">
            <a class="navbar-brand ml-4" href="/">BandMaker</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse content-center" id="navbarText">
                <ul class="navbar-nav d-flex bd-highlight">
                    <li class="nav-item active">';
        if ($banda) {
            echo '<a class="nav-link" href="/perfil-banda/' . $perfil[0]['nome_usuario'] . '">Banda: ' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
        } else {
            echo '<a class="nav-link" href="/perfil/' . $perfil[0]['nome_usuario'] . '">' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
        }

        echo '</li>';

        if ($banda || isset($perfil[0]['banda_id'])) {
            echo '<li class="nav-item bd-highlight">';
            echo '<a class="nav-link" href="/eventos/">Eventos</a>';
            echo '</li>';
        }
        if ($banda || !isset($perfil[0]['banda_id'])) {
            echo '<li class="nav-item bd-highlight">';
            echo '<a class="nav-link" href="/vagas/">Vagas</a>';
            echo '</li>';
        }
        echo '<li class="nav-item bd-highlight">';
        echo '<a class="nav-link" href="/notificacoes/">Notificações</a>';
        echo '</li>';

        echo '<li class="nav-item bd-highlight">';
        echo '<a class="nav-link" href="/logout">Deslogar</a>';
        echo '</li>';
        echo '</ul>
                    </div>
                </nav>
            </header>';
    } else {
        echo '
        <header id="beggining">
            <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
                <div class="mx-auto order-0">
                    <a class="navbar-brand mx-auto" href="/">BandMaker</a>
                </div>
            </nav>
        </header>
        ';
    }
    ?>

    <div class="container mt-5">

        <div class="row justify-content-center">

            <h1 class="mt-4">Perfil Profissional</h1>

        </div>

        <div class="row mt-4">
            <div class="col-sm-12 col-md-8 d-flex">
                <!-- Escreve informações do Perfil -->
                <?php
                echo '<img class src="../assets/profileImg/' . $perfilExibido[0]['imagem'] . '" width="185" height="145">';

                echo '<ul class="list-group list-group-vertical">';
                echo '<li class="list-group-item">' . $perfilExibido[0]['nome'] . ' // @' . $perfilExibido[0]['nome_usuario'] . '</li>';
                echo ' <li class="list-group-item">' . $perfilExibido[0]['email'] . '</li>';
                echo ' <li class="list-group-item">' . $perfilExibido[0]['estado'] . ' // ' . $perfilExibido[0]['cidade'] . '</li>';
                echo '</ul>';
                echo '<div class="card">';
                echo ' <div class="card-body">' . $perfilExibido[0]['influencia'] . '</div>';
                echo '</div>';
                ?>
            </div>

        </div>

        <div class="row mt-6 pt-5">

            <div class="col-sm-4 col-md-6 margin-left-0">
                <!-- Escreve informações do Perfil -->
                <?php
                echo '<ul class="list-group">';
                echo '<li class="list-group-item">Idade: ' . $perfilExibido[0]['idade'] . ' anos</li>';
                echo '<li class="list-group-item">Telefone: ' . $perfilExibido[0]['telefone'] . '</li>';
                echo '<li class="list-group-item">Instrumento: ' . $perfilExibido[0]['instrumento'] . '</li>';
                echo '<li class="list-group-item">Tempo que toca: ' . $perfilExibido[0]['tempo'] . ' anos</li>';
                echo '</ul>';

                ?>
            </div>

            <div class="col-sm-8 col-md-6 margin-left-0">
                <!-- Escreve qual banda pertence -->
                <?php
                if ($bandaParticipante == null) {
                    $bandaParticipante[0]['nome_usuario'] = "Nenhuma";
                    echo '<div class="card">';
                    echo '<h4 class="card-body">Banda: ' . $bandaParticipante[0]['nome_usuario'] . '';
                    echo '</h4>';                 
                    echo '</div>';
                }else {
                    echo '<div class="card">';
                    echo '<h4 class="card-body">Banda: ' . $bandaParticipante[0]['nome_usuario'] . '';
                    echo '<form method="post" action="/perfil/">';
                    echo '<button class="btn btn-danger" type="submit">Sair da banda</button>';
                    echo '</form>';
                    echo '</h4>';                 
                    echo '</div>';
                }
                ?>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer>
        <nav class="navbar fixed-bottom navbar-dark bg-dark p-0 mt-5">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright BandMaker 2019</a>
            </div>
        </nav>
    </footer>
</body>

<script src="../js/jquery-3.3.1.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>



</html>