<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <title>Banda</title>
</head>

<body>
    <!--Menu-->
    <?php
    if (isset($_SESSION['loginID'])) {
        echo '
        <header id="beggining">

        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark p-0">
            <a class="navbar-brand ml-4" href="/">BandMaker</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse content-center" id="navbarText">
                <ul class="navbar-nav d-flex bd-highlight">
                    <li class="nav-item active">';
        if ($banda) {
            echo '<a class="nav-link" href="/perfil-banda/' . $perfil[0]['nome_usuario'] . '">Banda: ' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
        } else {
            echo '<a class="nav-link" href="/perfil/' . $perfil[0]['nome_usuario'] . '">' . $perfil[0]['nome_usuario'] . '<span class="sr-only">(current)</span></a>';
        }

        echo '</li>';

        if ($banda || isset($perfil[0]['banda_id'])) {
            echo '<li class="nav-item bd-highlight">';
            echo '<a class="nav-link" href="/eventos/">Eventos</a>';
            echo '</li>';
        }
        if ($banda || !isset($perfil[0]['banda_id'])) {
            echo '<li class="nav-item bd-highlight">';
            echo '<a class="nav-link" href="/vagas/">Vagas</a>';
            echo '</li>';
        }
        echo '<li class="nav-item bd-highlight">';
        echo '<a class="nav-link" href="/notificacoes/">Notificações</a>';
        echo '</li>';

        echo '<li class="nav-item bd-highlight">';
        echo '<a class="nav-link" href="/logout">Deslogar</a>';
        echo '</li>';
        echo '</ul>
                    </div>
                </nav>
            </header>';
    } else {
        echo '
        <header id="beggining">
            <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
                <div class="mx-auto order-0">
                    <a class="navbar-brand mx-auto" href="/">BandMaker</a>
                </div>
            </nav>
        </header>
        ';
    }
    ?>


    <div class="container my-5">
        <!-- Nome e Gênero -->

        <div class="row">
            <div class="col-sm-12 col-md-8 d-flex">
                <?php
                echo '<img class="img-thumbnail" src="../assets/BandProfileImg/' . $perfilExibido[0]['imagem'] . '" width="200" height="150">';
                ?>
                <div class="text-center text-break p-4">
                    <?php
                    echo '<ul class="list-group">';
                    echo '<li class="list-group-item"><h3>' . $perfilExibido[0]['nome_usuario'] . '</h3></li>';
                    echo '<li class="list-group-item">' . $perfilExibido[0]['genero'] . '</li>';
                    echo '</ul>';
                    ?>
                </div>
            </div>
        </div>



        <!-- Informação -->
        <div class="row">
            <div class="col-sm-4 col-md-4 my-3 text-center text-break ">
                <!-- DEMO -->
                <?php
                if (isset($perfilExibido[0]['track'])) {

                    echo '<audio controls class="my-3">';
                    echo ' <source src="../assets/audio/' . $perfilExibido[0]['track'] . '" type="audio/mpeg">';
                    echo '</audio>';
                } else {
                    echo '<div class="col-sm-12 col-md-6">';
                    echo '<form method="post" action="/perfil-banda/" enctype="multipart/form-data">';
                    echo '<div class="border border-light border-radius-3">';
                    echo '<p class="text-secondary">Adicione uma Track da banda</p>';
                    echo '<div>';
                    echo '<input name="audio" type="file" id="audioload" accept="audio/*">';
                    echo '</div>';
                    echo '<button type="submit" class="btn btn-dark btn-lg w-25">Criar</button>';
                    echo '</div>';
                    echo '</form>';
                    echo '</div>';
                }
                ?>
                <?php
                echo '<ul class="list-group">';
                echo ' <li class="list-group-item"><b>' . $perfilExibido[0]['cidade'] . '/' . $perfilExibido[0]['estado'] . '</b></li>';
                echo '<li class="list-group-item"><b>Contato</b> <br>' . $perfilExibido[0]['telefone'] . '<br>' . $perfilExibido[0]['email'] . '</li>';
                echo '<li class="list-group-item"><b>Influências</b> <br> ' . $perfilExibido[0]['influencias'] . '</li>';
                echo '<li class="list-group-item"><b>Sobre a Banda</b> <br>' . $perfilExibido[0]['descricao'] . '</li>';
                echo '</ul>';
                ?>
            </div>

            <!-- integrantes -->
            <div class="col-sm-8 col-md-7 my-auto mx-auto">
                <?php
                foreach ($integrante as $key => $value) {
                    echo '<a class="text-reset nav-link" href="/perfil/' . $integrante[$key]['nome_usuario'] . '"><div class="card mb-3 py-1"> <div class="card-body"> <div class="row"> <div class="col-2">';
                    echo '<img class src="../assets/profileImg/' . $integrante[0]['imagem'] . '" width="100" height="100">';
                    echo ' </div> <div class="col-6 my-auto mx-auto"> <h6> ' . $integrante[$key]['nome_usuario'] . ' - ' . $integrante[$key]['instrumento'] . '</h6> </div> </div> </div> </div></a>';
                }
                ?>
            </div>
        </div>



    </div>

    <!-- Footer -->
    <footer>
        <nav class="navbar fixed-bottom navbar-dark bg-dark p-0 mt-5">
            <div class="mx-auto order-0">
                <a class="navbar-text mx-auto" href="#">&copy;Copyright BandMaker 2019</a>
            </div>
        </nav>
    </footer>

</body>
<script src="../js/jquery-3.3.1.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

</html>